

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Custom.Template:
            - Main
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        news:
          label: 'News'
  

  Flow:
    mvc:
      routes:
        'Custom.Template': true
        'Neos.Neos': false
        'Neos.Neos.Ui': false