

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Custom.Template:
            - Main
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        news:
          label: 'News'
  

  Flow:
    mvc:
      routes:
        'Custom.Template': true
        'Neos.Neos': false
        'Neos.Neos.Ui': false
  
  Fusion:
    defaultContext:
      'Custom.Template.Env': 'Custom\Template\Eel\EnvironmentHelper'
      'Custom.Template.Argument': 'Custom\Template\Eel\ArgumentHelper'
