#                                                                        #
# Default routes configuration for the Welcome package                   #
#                                                                        #

-
  name: 'happy screen'
  uriPattern: 'happy'
  defaults:
    '@package':    'Happy.Coding'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
    custom: true
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
-
  name: 'hello screen'
  uriPattern: 'hello'
  defaults:
    '@package':    'Happy.Coding'
    '@controller': 'Standard'
    '@action':     'hello'
    '@format':     'html'

-
  name: 'Backend'
  uriPattern: 'typo3/management/happymodule'
  defaults:
    '@package':    'Happy.Coding'
    '@controller': 'Backend'
    '@action':     'create'
    '@format':     'html'