#                                                                        #
# Default routes configuration for the Welcome package                   #
#                                                                        #

# frontend url: http://flow.test/happy
-
  name: 'happy screen'
  uriPattern: 'happy'
  defaults:
    '@package':    'Happy.Coding'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
    custom: true
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
# frontend url: http://flow.test/hello?name=<name>
-
  name: 'hello screen'
  uriPattern: 'hello'
  defaults:
    '@package':    'Happy.Coding'
    '@controller': 'Standard'
    '@action':     'hello'
    '@format':     'html'
# backend url: http://flow.test/typo3/management/happyModule
-
  name: 'Backend'
  uriPattern: 'typo3/management/happymodule'
  defaults:
    '@package':    'Happy.Coding'
    '@controller': 'Backend'
    '@action':     'create,edit,update,delete'
    '@format':     'html'