Neos:
  Flow:
    mvc:
      routes:
        'Happy.Coding':
          position: 'start'
  Neos:
    modules:
      'management':
        submodules:
          'happyModule':
            label: 'Custom Test News'
            controller: 'Happy\Coding\Controller\BackendController'
            description: 'neos custom module - news'
            icon: 'icon-newspaper'
    fusion:
      autoInclude:
        'Happy.Coding': true