
Neos:
  Flow:
    http:
      trustedProxies:
        proxies: '*'

    debugMode: true

Custom:
  Template:
    settings:
      development: true
      watchServe: false
      staging: false     # To enable Staging-Badge
      debugcss: false   # True needs vite serve `npm run watch-serve`
      noindex: true     # To force NOINDEX
