
Neos:
  Flow:
    http:
      trustedProxies:
        proxies: '*'

    debugMode: true

Custom:
  Template:
    settings:
      development: true
      staging: false     # To enable Staging-Badge
      debugcss: true   # True to enable debug.css (Break-Points)
      noindex: true     # To force NOINDEX
