
Neos:
  Flow:
    http:
      trustedProxies:
        proxies: '*'

    debugMode: true

Custom:
  Template:
    settings:
      development: true
      watchServe: true
      staging: false     # To enable Staging-Badge
      debugcss: true   # True needs vite serve `npm run watch-serve`
      noindex: true     # To force NOINDEX
