Neos:
  Neos:
    fusion:
      autoInclude:
        'Custom.Team': true
    userInterface:
      translation:
        autoInclude:
          Custom.Team:
            - Main
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        team:
          label: 'Team'