name: flow
type: php
docroot: Web
php_version: "8.1"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
additional_fqdns: [flow.test]
database:
  type: mariadb
  version: "10.4"
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - FLOW_CONTEXT=Development/Ddev
  - FLOW_PATH_TEMPORARY_BASE=/tmp/Flow
  - FLOW_REWRITEURLS=1
nodejs_version: "17"

hooks:
  post-start:
    - exec: composer install
    - exec: ./flow neos.flow:package:rescan
    - exec: ./flow database:setcharset
    - exec: ./flow doctrine:migrate