
Neos:
  Flow:
    http:
      trustedProxies:
        proxies: '*'

    debugMode: true

Custom:
  Template:
    settings:
      development: true
      staging: false     # To enable Staging-Badge
      debugcss: true   # True to enable debug.css (Break-Points)
      noindex: true     # To force NOINDEX

t3n:
  Neos:
    Debug:
      enabled: true
      htmlOutput:
        enabled: true
      serverTimingHeader:
        enabled: true
      sql:
        # Set when a query should be considered as slow query. In ms
        slowQueryAfter: 10